// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PullRequest struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	AuthorID          string             `json:"author_id"`
	Status            string             `json:"status"`
	AssignedReviewers []string           `json:"assigned_reviewers"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
}

type Team struct {
	Name string `json:"name"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}
